### PR TITLE
Move configuration and data to own file

### PR DESCRIPTION
**Pull request by michpappas**
This series performs the following updates:

- Move configuration and data into own file
- Move tests into file and create separate build
- Separate personalize and auxiliary commands away from core commands
- Implement end-user s06-204 utility
- Refactor test cases to compute expected values

### CODE REVIEW

**Comment by michpappas** [comment]
@jbech-linaro sorry for the travis error, updating now

**Comment by michpappas** [comment]
@jbech-linaro fixed. BTW, I noticed this comment:

>  +/* Generated by ATSHA204A slot config generator */ 

I haven't been able to find anything relevant online, but it looks like some tool can be used to aid users generating configs?

**Comment by jbech-linaro** [comment]
> I haven't been able to find anything relevant online, but it looks like some tool can be used to aid users generating configs?

When I got the device I started the development in another Git, but as we were getting closer to Linaro Connect where we were going to show this, I cleaned it up a bit and created a new git repository for it.  Having that said, my old stuff is still there and the script you are asking about can be found here:
https://github.com/jbech-linaro/secmess/blob/slotconfig/slotconfig.py

**Comment by michpappas** [comment]
Ah okay, I thought it was some tool developed by Atmel / Microchip that I wasn't aware of

**Comment by michpappas** [comment]
@jbech-linaro pushed a few more as series of commits as they all depend on the first one

**Comment by michpappas** [comment]
@jbech-linaro, since you didn't review this yet I added one more commit and restructured things a bit to hopefully make it easier for review.

**Comment by michpappas** [comment]
Although some parts have been reworked a lot, I think the most obtrusive change is moving personalize and auxiliary command functions away from the core librarly. I only left the functions that implement the core commands of the atsha204a in cmd.c. The functions moved to main.c can be used as examples of how one could use the core commands to implement more complex functions.
Alternatively, we could hide the core commands and implement a higher level of abstraction with functions such as atsha_personalize() etc, but in any case I think it's better to clearly separate the two. Let me know what you think.

**Comment by michpappas** [comment]
Regarding travis:

- If these changes get merged, we'll need to add a rule to build the tests too
- I've had several occasions already where travis failed because I'm using some c99 constructs. Mainly declare the counter inside the loop header. What are your views on c99?

**Comment by michpappas** [comment]
Sample output from the util:
```
root@beaglebone:/tmp# /tmp/s96-204 -h
Usage: /tmp/s96-204 <option>

Available options:
  -i, --info           Display device info
  -d, --dump-config     Dump config zone
  -p, --personalize    Write config and data
  -h, --help           Display this message
  -v, --version        Display version
```

```
root@beaglebone:/tmp# /tmp/s96-204 -i
ATSHA204A on /dev/i2c-1 @ addr 0x64
Device Revision:    00020009
Serial Number:      01233ac589d557d8ee
Config Zone locked:  Yes
Data Zone locked:   Yes
OTP mode:           Consumption
```
```
root@beaglebone:/tmp# /tmp/s96-204 -d | xxd
0000000: 0123 3ac5 0009 0400 89d5 57d8 ee12 0100  .#:.......W.....
0000010: c800 5500 8080 80a0 8042 a043 8020 80a0  ..U......B.C. ..
0000020: 8030 80b0 8048 c049 8080 8080 0000 0000  .0...H.I........
0000030: 0080 0080 ff00 ff00 ff00 0000 ff19 ff00  ................
0000040: ff28 ff00 ffff ffff ffff ffff ffff ffff  .(..............
0000050: ffff ffff ff00 0000                      ........
```

**Comment by michpappas** [comment]
Speaking of the tests, they are not really comprehensive nor sophisticated, but for the time being I think they will do. I'd also rather not spend more time on this and move on to atsha508a, which from a first look it seems to have overlapping functionality with atsha508a, so probably we'll be able to reuse a lot of the existing code.

**Comment by michpappas** [comment]
@jbech-linaro did you have the chance to have a look at this?

Lately the idea of a high level library gets more and more appealing to me. I think it suits better the aim of the project. What I have in mind is something along the lines of this:

https://gist.github.com/michpappas/cdc983a576c67a92a178b2f70343ae0d

Notice how the low-level details are abstracted away, eg in s96at_get_mac(), while flexibility is still there.

If you agree with this approach please close this PR and I will create a new patch-set based on the above.

**Comment by michpappas** [comment]
Just to be clear, the above is the public library API that would internally use the core device commands implemented in cmd.c

**Comment by jbech-linaro** [comment]
Hi @michpappas , sorry for the delayed answer, had a couple of days off. I think this is a nice clean-up and looks a lot better than it has been doing until now. I'd be happy to merge this.



> I've had several occasions already where travis failed because I'm using some c99 constructs. Mainly declare the counter inside the loop header. What are your views on c99?

I'm definitely pro using new (feels silly to say "new", when talking about something that is still really old) language features. So feel free to enable c99 (and thereby get rid of Travis errors etc).



> Lately the idea of a high level library gets more and more appealing to me. I think it suits better the aim of the project. What I have in mind is something along the lines of this:

So here I guess you are referring to my idea of creating libraries that "other" apps can link against? Your proposal gist looks nice and clean.  Question, since you suggest to prefix things with s96, did you plan to use the same interface as much as possible for the 204 and the 508?

**Comment by michpappas** [comment]
@jbech-linaro no problem, good to hear back from you. Since you are happy with the proposed interface, I'll provide new patches that will implement that as well as the ones included on this one. I am still not entirely happy with the current set regarding cleaningness and ease for review, so please feel free to close the current PR. I'll come up with smaller ones.

> I'm definitely pro using new (feels silly to say "new", when talking about something that is still really old) language features. So feel free to enable c99 (and thereby get rid of Travis errors etc).

Great, will do.

> So here I guess you are referring to my idea of creating libraries that "other" apps can link against? 

Yes, I think it would be nice to be able to do so.

> Your proposal gist looks nice and clean. Question, since you suggest to prefix things with s96, did you plan to use the same interface as much as possible for the 204 and the 508?

Indeed. I forgot to mention that the other day, but I had a look at the reference of the 508 and I noticed that it is actually backwards compatible with the 208. See Section 10 in 

http://ww1.microchip.com/downloads/en/DeviceDoc/20005927A.pdf

I gave it a quick try and the new tests pass already. The 204 util (the new main) works with minor modifications too, it only required to change the size of the config zone. This means we can use the same library to support both 204 and 508 (along with the 108 and all the rest that are not relevant to our case). This is what [cryptoauthlib](https://github.com/MicrochipTech/cryptoauthlib) does too. 
All we need a name for that would cover both. I quickly came up with s96at (s96auth could be another candidate?) but please let me know if you have any suggestions for a name you'd find more suitable.

One more thing that is not necessarily for the present: Since we have two modules that support common functionality (the SHA command set), once the library is complete we can provide some code examples of common use cases of host-client interaction, eg modules share the same parent key and perform MAC verification using euphemeral keys.

**Pull request closed without merging**
