### PR TITLE
Introducing the s96at library

### PR DESCRIPTION
**Pull request by michpappas**
This series introduces the s96at library, along with some required tidy-up in the implementation of the core commands. Tests are updated to use the library API and new cases are added.

### CODE REVIEW

**Comment by michpappas** [comment]
@jbech-linaro also updated travis.yml to build successfully

**Comment by michpappas** [comment]
@jbech-linaro reagarding the discussion we had earlier on C99, are you happy with using the GNU extensions? (ie gnu99)

**Comment by jbech-linaro** [comment]
@michpappas , this is really great! Thanks a lot for taking the time to do all this. Having it as a library makes it easy to use from whatever tool you want to use/develop. Good job!

> @jbech-linaro reagarding the discussion we had earlier on C99, are you happy with using the GNU extensions? (ie gnu99)

Yes!

I've reviewed the patches and I'd be happy merge this. Anything else you want to add to the PR or should I press the button?

**Comment by michpappas** [comment]
@jbech-linaro glad you like it, please merge. More patches on the way :-)

**Pull request merged**
