### PR TITLE
Complete the implementation of cmd_write()

### PR DESCRIPTION
**Pull request by michpappas**
- Add encrypt flag
- Set length bit on 32 byte writes
- Remove duplicate set of timing
- Call write through at204_msg() to enquire the device for
  the command status

Signed-off-by: Michalis Pappas <mpappas@fastmail.fm>

### CODE REVIEW

**Comment by michpappas** [comment]
@jbech-linaro this is related to the issues with CRC and LOCK, as some writes would return Execute Error, which was uncaught until now, and the computed CRC would therefore not correspond to the data actually stored in the device.

**Comment by michpappas** [comment]
@jbech-linaro the second commit fixes the remaining issues with CRC, it should all now work correctly

**Comment by michpappas** [comment]
The CRC algorithm adopted by various projects can be found at: http://ww1.microchip.com/downloads/en/AppNotes/Atmel-8936-CryptoAuth-Data-Zone-CRC-Calculation-ApplicationNote.pdf

**Comment by jbech-linaro** [comment]
Closing this PR since I've merged the patches manually. Thanks for yet another contribution!

Btw, I've added a .travis file today, so all PR's are built now. On my own computer I see no warnings, but on Travis there are some showing warnings about logd. I should fix those at some point, so there is a clean build in Travis also.

**Comment by michpappas** [comment]
@jbech-linaro I saw the travis file yesterday, good to see the project getting into shape.
Btw, while working on this, I also wrote a sigrok decoder for atsha204a. If you are interested, you can find it here:

https://github.com/michpappas/atsha204a_sigrok_decoder

I need to polish a couple of things before I submit it for inclusion to sigrok, but other than that the current version is fully functional.

**Comment by jbech-linaro** [comment]
> @jbech-linaro I saw the travis file yesterday, good to see the project getting into shape.

It's you that should have credits for that :)

> I also wrote a sigrok decoder for atsha204a.

Cool! That's really useful. I was sitting with a [bus blaster](http://dangerousprototypes.com/docs/Bus_Blaster_v3_design_overview) in the initial phase to sniff the packets and I also used logical analyzer, but your script here is way better, since the parsing is done automatically. Well done!

**Pull request closed without merging**
